name: Pytest

on: [push]

jobs:
  docker_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run unit tests
        run: docker build . --file docker/unittest.Dockerfile --tag unittest
        env:
          ENABLE_SLOW_TESTS: True

  ubuntu_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --without deploy,dev --with test
    - name: Running the tests with pytest
      run: poetry run pytest
